//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/MainMenuControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MainMenuControl : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MainMenuControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MainMenuControl"",
    ""maps"": [
        {
            ""name"": ""Menu"",
            ""id"": ""60940e2d-16ff-4984-9b31-e835c7cea716"",
            ""actions"": [
                {
                    ""name"": ""PressStart"",
                    ""type"": ""Button"",
                    ""id"": ""228b32f5-ba4e-460b-b1a7-1b63fe8a9c65"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""554d5756-f3e0-4886-b45e-55cc29e42c93"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Menu
        m_Menu = asset.FindActionMap("Menu", throwIfNotFound: true);
        m_Menu_PressStart = m_Menu.FindAction("PressStart", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Menu
    private readonly InputActionMap m_Menu;
    private IMenuActions m_MenuActionsCallbackInterface;
    private readonly InputAction m_Menu_PressStart;
    public struct MenuActions
    {
        private @MainMenuControl m_Wrapper;
        public MenuActions(@MainMenuControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @PressStart => m_Wrapper.m_Menu_PressStart;
        public InputActionMap Get() { return m_Wrapper.m_Menu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuActions set) { return set.Get(); }
        public void SetCallbacks(IMenuActions instance)
        {
            if (m_Wrapper.m_MenuActionsCallbackInterface != null)
            {
                @PressStart.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnPressStart;
                @PressStart.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnPressStart;
                @PressStart.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnPressStart;
            }
            m_Wrapper.m_MenuActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PressStart.started += instance.OnPressStart;
                @PressStart.performed += instance.OnPressStart;
                @PressStart.canceled += instance.OnPressStart;
            }
        }
    }
    public MenuActions @Menu => new MenuActions(this);
    public interface IMenuActions
    {
        void OnPressStart(InputAction.CallbackContext context);
    }
}
